package:
  name: tiledb

source:
  git_rev: dev
  git_url: https://github.com/TileDB-Inc/TileDB.git

requirements:
  build:
    - cmake >= 2.8
    - openssl
    - zlib
    - bzip2
    - zstd
    - snappy
    - blosc

  run:
    - openssl
    - zlib
    - bzip2
    - zstd
    - snappy
    - blosc

about:
  home: http://www.tiledb.org
  license: MIT
  summary: Scientific data management made easy
