package:
  name: tiledb
  version: dev

source:
  git_rev: dev
  git_url: https://github.com/TileDB-Inc/TileDB.git

requirements:
  build:
    - cmake >=2.8
    - zlib
    - bzip2
    - zstd
    - snappy
    - lz4-c
    - blosc

  run:
    - zlib
    - bzip2
    - zstd
    - snappy
    - lz4-c
    - blosc

about:
  home: http://www.tiledb.io
  license: MIT
  summary: Scientific data management made fast and easy
